### PR TITLE
login_scrub for clan symbolic, first implementation of new newbie quest

### PR DESCRIPTION
**Pull request by chrisspanton**

### CODE REVIEW

**Comment by chrisspanton** [comment]
added fixes for #83 immortal starvation

**Comment by chrisspanton** [comment]
Added first push of the work-in-progress Barbarian Guild

**Review by Seifert69 — APPROVED** [review]
That's fantastic. :-)) Thank you so much!

**Comment by Seifert69** [comment]
Really fantastic. I look forward to trying it out :-)))

**Pull request merged**
