### PR TITLE
Pr unit tests for color_type() and for CServerConfiguration()

### PR DESCRIPTION
**Pull request by bluedreamer**
Added some unit tests for color_type() and for CServerConfiguration()

### CODE REVIEW

**Review by Seifert69 — APPROVED** [review]
Thank you. :)

**Comment by Seifert69** [comment]
Oh that auto build is nice :) Looks like it resulted in a build-error :))

**Comment by bluedreamer** [comment]
It is great - otherwise it would have been "worked on my machine" :-)

Digging through the issues now

**Review by Seifert69 — APPROVED** [review]
Thanks :)

**Pull request merged**
