### PR TITLE
Web Client Updates

### PR DESCRIPTION
**Pull request by Fizzie68**
I have updated the web client to allow for style sheet changes.  I also included a Silver Style Theme as an example.  The really hard part will be building different themes.  I have not play tested the new style.  Let me know if this is not what you were looking for.

Dave

### CODE REVIEW

**Comment by Fizzie68** [comment]
I am using on my test mud ht http:\\titan.starpoint.net/diku if you want to look at it in action.

**Comment by Seifert69** [comment]
Fantastic :-)

I'm wondering if we can get rid of the top bar to allow more space for
scrolling & reading.

I was wondering if you can make a link to settings in the right hand bar.
The settings window will allow you to pick a theme?

Also, I noticed in Firefox, the text overlay on the HP, MP, EP becomes
jumbled.

Let me know what you think and if you need any assistance.

**Comment by Fizzie68** [comment]
A little disappointed that you did not care for the banner bar, but I have made the changes that you requested.  Take a look and let me know what you think.

Dave

**Comment by Fizzie68** [comment]
Oh yeah, as for disabling that security warning in FIrefox.  It is a warning that can be disabled in the firefox advanced settings:  https://www.ghacks.net/2017/06/13/firefox-disable-this-connection-is-not-secure-warnings/

**Comment by Seifert69** [comment]
Thank you. I think it's best to keep it clean. Also for the sake of the
accessibility mode.

I'll check it out tonight :-)

**Thanks**

**Comment by Seifert69** [comment]
If you like the bar then maybe the settings button can simply show / hide
it? That works for me too :-)

**Comment by Fizzie68** [comment]
I gave your last suggestion a try.  Tell me what you think:
http://titan.starpoint.net/diku/client-b.html

**Comment by Seifert69** [comment]
Functionally I think it is good.

I'm also happy if you'd rather toggle the visibility of the top-bar.

Just submit the version you personally like the best :-)

**Thank you**

**Comment by Fizzie68** [comment]
Ok.  Done

**Comment by Seifert69** [comment]
Two things I've noticed:

1) In Chrome there's a gap at the bottom, which fills out when you show the
bar.
2) In firefox the bar is too slim and the text barely shows

I'm no HTML expert :-) Is it better to make it an overlay?

**Comment by Fizzie68** [comment]
I am noticing that now that I am using it tonight.  It is annoying.  I will
submit the version with a pop-up modal window and keep working on this one.

Dave

**Comment by Seifert69** [comment]
Thanks. I'm aware of that. I have a suspicion though, that if we ask for
the pwd in a different text box, rather than changing the type, then I dont
think the warning will pop-over the input field. I think the warning only
appears because the field intermittently was changed to "hidden". Just a
hunch. I dont know if it turns out to be so.

**Pull request merged**
